title:              René's Portfolio
email:              renedcdsl@hotmail.fr
description:        My Data Science projects
author:             René de Champs
baseurl:            ""
url:                "https://renedc.github.io"

# Social Profiles
#twitter_username:   
github_username:    ReneDCDSL
facebook_username:  René de Champs
#instagram_username:  
linkedin_username:  René de Champs

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
